# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pipeline CI/CD (AWS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    AS_API_NAME: as-users-api
    AS_API_DOCKERFILE: ./AS.Users.API/Dockerfile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./as-users-api.sln

    - name: Build
      run: dotnet build ./as-users-api.sln --no-restore

    - name: Test
      run: dotnet test ./as-users-api.sln --no-build --verbosity normal

  deploy:
    name: Deploy to Production
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Login na AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    # Login no ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # Build & Push da API
    - name: Build and push API image
      run: |
        docker build -t ${{env.AS_API_NAME}} -f ${{env.AS_API_DOCKERFILE}} .
        docker tag ${{env.AS_API_NAME}}:latest ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{env.AS_API_NAME}}:latest
        docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{env.AS_API_NAME}}:latest

    # Configura kubectl para EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name ${{ vars.EKS_CLUSTER_NAME }} \
          --region ${{ vars.AWS_REGION }}
    
    - name: Render Kubernetes manifest
      env:
        AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        mkdir -p rendered
        envsubst < k8s/users-api-deployment.yaml > rendered/users-api-deployment.yaml
        cp k8s/users-api-config.yaml rendered/users-api-config.yaml
        cp k8s/users-api-service.yaml rendered/users-api-service.yaml

    # Deploy no Kubernetes
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f rendered/
